version: '3'
services:
  node_mig:
    build: .
    container_name: node-migration
    command: sh -c "yarn start"
    ports:
      - 8080:3000
    volumes:
      - ./:/app
    depends_on:
      - db
    tty: true
  db:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./tmp/db:/var/lib/mysql
      - ./build/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./build/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306